[package]
name = "egg_for_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.9.2"
lazy_static = "1.4.0"
trans_expr = { path = "../trans_expr"}
